name: API Test Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Create configuration.properties in root
        run: |
          echo "baseUrl=https://api.openweathermap.org/data/2.5" > configuration.properties
          echo "weather.api.key=${{ secrets.API_KEY }}" >> configuration.properties
      

      - name: Debug config file
        run: cat configuration.properties

      - name: Run Maven Tests
        run: mvn clean verify

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports/
